### ISSUE TITLE
Google play services is not available. this application will close.

### ISSUE THREAD

**Issue by ananth10** [googlearchive/gplus-quickstart-android#24]
getting this error when i click "Sign in " button.

**Comment by ananth10** [comment]
![device-2015-09-26-203156](https://cloud.githubusercontent.com/assets/13381242/10118131/bbc152e8-648d-11e5-966e-356ccaa07b4d.png)

**Comment by vivekkiran** [comment]
You have to create a Signing certificate fingerprint(SHA1) using the keytool in the terminal app and try running the app. More on this link(https://developers.google.com/+/mobile/android/getting-started#step_1_enable_the_google_api).

**Comment by ananth10** [comment]
Ok. Thanks Vivek.

**Comment by ananth10** [comment]
I have solved this issue by creating oauth client id.

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
